export const CHARACTER_LIST_REQUEST = 'CHARACTER_LIST_REQUEST';
export const CHARACTER_LIST_SUCCESS = 'CHARACTER_LIST_SUCCESS';
export const CHARACTER_LIST_FAIL = 'CHARACTER_LIST_FAIL';

export const CHARACTER_INFO_REQUEST = 'CHARACTER_INFO_REQUEST';
export const CHARACTER_INFO_SUCCESS = 'CHARACTER_INFO_SUCCESS';
export const CHARACTER_INFO_FAIL = 'CHARACTER_INFO_FAIL';
