export const CHARACTER_LIST_REQUEST = 'CHARACTER_LIST_REQUEST';
export const CHARACTER_LIST_SUCCESS = 'CHARACTER_LIST_SUCCESS';
export const CHARACTER_LIST_FAIL = 'CHARACTER_LIST_FAIL';

export const CHARACTER_INFO_REQUEST = 'CHARACTER_INFO_REQUEST';
export const CHARACTER_INFO_SUCCESS = 'CHARACTER_INFO_SUCCESS';
export const CHARACTER_INFO_FAIL = 'CHARACTER_INFO_FAIL';
export const CHARACTER_INFO_RESET = 'CHARACTER_INFO_RESET';

export const CHARACTER_DELETE_REQUEST = 'CHARACTER_DELETE_REQUEST';
export const CHARACTER_DELETE_SUCCESS = 'CHARACTER_DELETE_SUCCESS';
export const CHARACTER_DELETE_FAIL = 'CHARACTER_DELETE_FAIL';

export const CHARACTER_CREATE_REQUEST = 'CHARACTER_CREATE_REQUEST';
export const CHARACTER_CREATE_SUCCESS = 'CHARACTER_CREATE_SUCCESS';
export const CHARACTER_CREATE_FAIL = 'CHARACTER_CREATE_FAIL';
export const CHARACTER_CREATE_RESET = 'CHARACTER_CREATE_RESET';

export const CHARACTER_UPDATE_REQUEST = 'CHARACTER_UPDATE_REQUEST';
export const CHARACTER_UPDATE_SUCCESS = 'CHARACTER_UPDATE_SUCCESS';
export const CHARACTER_UPDATE_FAIL = 'CHARACTER_UPDATE_FAIL';
export const CHARACTER_UPDATE_RESET = 'CHARACTER_UPDATE_RESET';
