export const FILM_LIST_REQUEST = 'FILM_LIST_REQUEST';
export const FILM_LIST_SUCCESS = 'FILM_LIST_SUCCESS';
export const FILM_LIST_FAIL = 'FILM_LIST_FAIL';

export const FILM_INFO_REQUEST = 'FILM_INFO_REQUEST';
export const FILM_INFO_SUCCESS = 'FILM_INFO_SUCCESS';
export const FILM_INFO_FAIL = 'FILM_INFO_FAIL';
export const FILM_INFO_RESET = 'FILM_INFO_RESET';

export const FILM_DELETE_REQUEST = 'FILM_DELETE_REQUEST';
export const FILM_DELETE_SUCCESS = 'FILM_DELETE_SUCCESS';
export const FILM_DELETE_FAIL = 'FILM_DELETE_FAIL';

export const FILM_CREATE_REQUEST = 'FILM_CREATE_REQUEST';
export const FILM_CREATE_SUCCESS = 'FILM_CREATE_SUCCESS';
export const FILM_CREATE_FAIL = 'FILM_CREATE_FAIL';
export const FILM_CREATE_RESET = 'FILM_CREATE_RESET';

export const FILM_UPDATE_REQUEST = 'FILM_UPDATE_REQUEST';
export const FILM_UPDATE_SUCCESS = 'FILM_UPDATE_SUCCESS';
export const FILM_UPDATE_FAIL = 'FILM_UPDATE_FAIL';
export const FILM_UPDATE_RESET = 'FILM_UPDATE_RESET';
