export const PLANET_LIST_REQUEST = 'PLANET_LIST_REQUEST';
export const PLANET_LIST_SUCCESS = 'PLANET_LIST_SUCCESS';
export const PLANET_LIST_FAIL = 'PLANET_LIST_FAIL';

export const PLANET_INFO_REQUEST = 'PLANET_INFO_REQUEST';
export const PLANET_INFO_SUCCESS = 'PLANET_INFO_SUCCESS';
export const PLANET_INFO_FAIL = 'PLANET_INFO_FAIL';
export const PLANET_INFO_RESET = 'PLANET_INFO_RESET';

export const PLANET_DELETE_REQUEST = 'PLANET_DELETE_REQUEST';
export const PLANET_DELETE_SUCCESS = 'PLANET_DELETE_SUCCESS';
export const PLANET_DELETE_FAIL = 'PLANET_DELETE_FAIL';

export const PLANET_CREATE_REQUEST = 'PLANET_CREATE_REQUEST';
export const PLANET_CREATE_SUCCESS = 'PLANET_CREATE_SUCCESS';
export const PLANET_CREATE_FAIL = 'PLANET_CREATE_FAIL';
export const PLANET_CREATE_RESET = 'PLANET_CREATE_RESET';

export const PLANET_UPDATE_REQUEST = 'PLANET_UPDATE_REQUEST';
export const PLANET_UPDATE_SUCCESS = 'PLANET_UPDATE_SUCCESS';
export const PLANET_UPDATE_FAIL = 'PLANET_UPDATE_FAIL';
export const PLANET_UPDATE_RESET = 'PLANET_UPDATE_RESET';
