export const PLANET_LIST_REQUEST = 'PLANET_LIST_REQUEST';
export const PLANET_LIST_SUCCESS = 'PLANET_LIST_SUCCESS';
export const PLANET_LIST_FAIL = 'PLANET_LIST_FAIL';

export const PLANET_INFO_REQUEST = 'PLANET_INFO_REQUEST';
export const PLANET_INFO_SUCCESS = 'PLANET_INFO_SUCCESS';
export const PLANET_INFO_FAIL = 'PLANET_INFO_FAIL';
export const PLANET_INFO_RESET = 'PLANET_INFO_RESET';
