export const SPECIES_LIST_REQUEST = 'SPECIES_LIST_REQUEST';
export const SPECIES_LIST_SUCCESS = 'SPECIES_LIST_SUCCESS';
export const SPECIES_LIST_FAIL = 'SPECIES_LIST_FAIL';

export const SPECIES_INFO_REQUEST = 'SPECIES_INFO_REQUEST';
export const SPECIES_INFO_SUCCESS = 'SPECIES_INFO_SUCCESS';
export const SPECIES_INFO_FAIL = 'SPECIES_INFO_FAIL';
export const SPECIES_INFO_RESET = 'SPECIES_INFO_RESET';

export const SPECIES_DELETE_REQUEST = 'SPECIES_DELETE_REQUEST';
export const SPECIES_DELETE_SUCCESS = 'SPECIES_DELETE_SUCCESS';
export const SPECIES_DELETE_FAIL = 'SPECIES_DELETE_FAIL';

export const SPECIES_CREATE_REQUEST = 'SPECIES_CREATE_REQUEST';
export const SPECIES_CREATE_SUCCESS = 'SPECIES_CREATE_SUCCESS';
export const SPECIES_CREATE_FAIL = 'SPECIES_CREATE_FAIL';
export const SPECIES_CREATE_RESET = 'SPECIES_CREATE_RESET';

export const SPECIES_UPDATE_REQUEST = 'SPECIES_UPDATE_REQUEST';
export const SPECIES_UPDATE_SUCCESS = 'SPECIES_UPDATE_SUCCESS';
export const SPECIES_UPDATE_FAIL = 'SPECIES_UPDATE_FAIL';
export const SPECIES_UPDATE_RESET = 'SPECIES_UPDATE_RESET';
