export const STARSHIP_LIST_REQUEST = 'STARSHIP_LIST_REQUEST';
export const STARSHIP_LIST_SUCCESS = 'STARSHIP_LIST_SUCCESS';
export const STARSHIP_LIST_FAIL = 'STARSHIP_LIST_FAIL';

export const STARSHIP_INFO_REQUEST = 'STARSHIP_INFO_REQUEST';
export const STARSHIP_INFO_SUCCESS = 'STARSHIP_INFO_SUCCESS';
export const STARSHIP_INFO_FAIL = 'STARSHIP_INFO_FAIL';
export const STARSHIP_INFO_RESET = 'STARSHIP_INFO_RESET';

export const STARSHIP_DELETE_REQUEST = 'STARSHIP_DELETE_REQUEST';
export const STARSHIP_DELETE_SUCCESS = 'STARSHIP_DELETE_SUCCESS';
export const STARSHIP_DELETE_FAIL = 'STARSHIP_DELETE_FAIL';

export const STARSHIP_CREATE_REQUEST = 'STARSHIP_CREATE_REQUEST';
export const STARSHIP_CREATE_SUCCESS = 'STARSHIP_CREATE_SUCCESS';
export const STARSHIP_CREATE_FAIL = 'STARSHIP_CREATE_FAIL';
export const STARSHIP_CREATE_RESET = 'STARSHIP_CREATE_RESET';

export const STARSHIP_UPDATE_REQUEST = 'STARSHIP_UPDATE_REQUEST';
export const STARSHIP_UPDATE_SUCCESS = 'STARSHIP_UPDATE_SUCCESS';
export const STARSHIP_UPDATE_FAIL = 'STARSHIP_UPDATE_FAIL';
export const STARSHIP_UPDATE_RESET = 'STARSHIP_UPDATE_RESET';
