export const VEHICLE_LIST_REQUEST = 'VEHICLE_LIST_REQUEST';
export const VEHICLE_LIST_SUCCESS = 'VEHICLE_LIST_SUCCESS';
export const VEHICLE_LIST_FAIL = 'VEHICLE_LIST_FAIL';

export const VEHICLE_INFO_REQUEST = 'VEHICLE_INFO_REQUEST';
export const VEHICLE_INFO_SUCCESS = 'VEHICLE_INFO_SUCCESS';
export const VEHICLE_INFO_FAIL = 'VEHICLE_INFO_FAIL';
export const VEHICLE_INFO_RESET = 'VEHICLE_INFO_RESET';

export const VEHICLE_DELETE_REQUEST = 'VEHICLE_DELETE_REQUEST';
export const VEHICLE_DELETE_SUCCESS = 'VEHICLE_DELETE_SUCCESS';
export const VEHICLE_DELETE_FAIL = 'VEHICLE_DELETE_FAIL';

export const VEHICLE_CREATE_REQUEST = 'VEHICLE_CREATE_REQUEST';
export const VEHICLE_CREATE_SUCCESS = 'VEHICLE_CREATE_SUCCESS';
export const VEHICLE_CREATE_FAIL = 'VEHICLE_CREATE_FAIL';
export const VEHICLE_CREATE_RESET = 'VEHICLE_CREATE_RESET';

export const VEHICLE_UPDATE_REQUEST = 'VEHICLE_UPDATE_REQUEST';
export const VEHICLE_UPDATE_SUCCESS = 'VEHICLE_UPDATE_SUCCESS';
export const VEHICLE_UPDATE_FAIL = 'VEHICLE_UPDATE_FAIL';
export const VEHICLE_UPDATE_RESET = 'VEHICLE_UPDATE_RESET';
